// lib/rooms.ts
export const rooms = [
  {
    id: 1,
    slug: "deodar",
    name: "Deodar",
    category: "Premium Room",
    size: "484 sq ft.",
    view: "Mountain View",
    floor: "Ground Floor",
    description:
      "Deo means God and Dar means a tree, in other words; the celestial tree or the tree of the gods, which only makes it befitting that we name our most premium room after this magnificent tree. A very spacious room with cool things like bay windows for you to sit and soak the winter sun while enjoying the view of the snow-capped mountains, an electric fireplace, and a very spacious and modern washroom make this a truly luxurious room to stay in.",
    facilities: [
      "Three-seater sofa",
      "Glass cubicle for bathing",
      "Sofa cum bed",
      "Cupboards with hangers in rooms & washroom",
      "2 bay windows with seating",
      "Electric fireplace",
    ],
    images: [
      "/images/rooms/deodar-1.jpg",
      "/images/rooms/deodar-2.jpg",
      "/images/rooms/deodar-3.jpg",
      "/images/rooms/deodar-4.jpg",
      "/images/rooms/deodar-5.jpg",
    ],
  },
  {
    id: 2,
    slug: "buransh",
    name: "Buransh",
    category: "Premium Room",
    size: "484 sq ft.",
    view: "Mountain View",
    floor: "First Floor",
    description:
      "This room truly represents the experience that is Himalayan Shire. With an electric fireplace, bay windows and sofa lounge, handpicked carpets and fabrics, Buransh is as vibrant as the flower it’s named after. The most spacious room of our property it’s perfect for those who live life king size.",
    facilities: [
      "Electric fireplace",
      "Glass cubicle for bathing",
      "Sofa cum bed",
      "Cupboards with hangers in rooms & washroom",
      "Three-seater sofa",
      "2 bay windows with seating",
    ],
    images: [
      "/images/rooms/buransh-1.jpg",
      "/images/rooms/buransh-2.jpg",
      "/images/rooms/buransh-3.jpg",
      "/images/rooms/buransh-4.jpg",
      "/images/rooms/buransh-5.jpg",
    ],
  },
  {
    id: 3,
    slug: "chir-pine",
    name: "Chir Pine",
    category: "Deluxe Room",
    size: "300 sq ft.",
    view: "Mountain View",
    floor: "First Floor",
    description:
      "Located on the first floor, this deluxe room offers the best view of the mountains. Offering a bay window, sofa chairs, luggage stand, big cupboard, and a very stylish washroom with shower the room is a truly premium one. The view from this rooms will make you an early riser, if only to watch the beautiful sunrise.",
    facilities: [
      "Bay windows with seating",
      "Space for extra beddings",
      "2 seater sofa",
      "Luggage stand",
      "Stylish washroom with shower",
    ],
    images: [
      "/images/rooms/chir-pine-4.jpg",
      "/images/rooms/chir-pine-1.jpg",
      "/images/rooms/chir-pine-2.jpg",
      "/images/rooms/chir-pine-3.jpg",
      "/images/rooms/chir-pine-5.jpg",
    ],
  },
  {
    id: 4,
    slug: "blue-pine",
    name: "Blue Pine",
    category: "Deluxe Room",
    size: "300 sq ft.",
    view: "Valley View",
    floor: "Ground Floor",
    description:
      "Named after the most pre-dominant pine species found around our property, this room offer a valley-view right from your bed. Spacious room with a king size bed, cupboards, luggage stand, and a very beautiful bathroom, this room will make your stay a more joyful one.",
    facilities: [
      "Space for extra beddings",
      "Handrails in washroom for elderly",
      "Bay window with seating",
      "King size bed",
      "Valley view from bed",
    ],
    images: [
      "/images/rooms/bluepine-1.jpg",
      "/images/rooms/bluepine-2.jpg",
      "/images/rooms/bluepine-3.jpg",
      "/images/rooms/bluepine-4.jpg",
      "/images/rooms/bluepine-5.jpg",
    ],
  },
  {
    id: 5,
    slug: "walnut",
    name: "Walnut",
    category: "Standard Room",
    size: "300 sq ft.",
    view: "Garden View",
    floor: "Ground Floor",
    description:
      "Located on the ground floor, this room is easily accessible even by those who have trouble climbing stairs. Having a very cozy interior, with handpicked carpets, big cupboards, and a very stylish bathroom, this room feels like home.",
    facilities: [
      "Space for extra bedding",
      "King size bed",
      "Luggage stand",
      "Stylish bathroom",
      "Easily accessible",
    ],
    images: [
      "/images/rooms/walnut-1.jpg",
      "/images/rooms/walnut-2.jpg",
      "/images/rooms/walnut-3.jpg",
      "/images/rooms/walnut-4.jpg",
      "/images/rooms/walnut-5.jpg",
    ],
  },
  {
    id: 6,
    slug: "mohru",
    name: "Mohru",
    category: "Standard Room",
    size: "300 sq ft.",
    view: "Mountain View",
    floor: "First Floor",
    description:
      "A cozy standard room named after the local Mohru tree, offering warm wooden interiors and a comfortable stay. It features handpicked carpets and a beautiful view, making it a serene retreat after a day in the mountains.",
    facilities: [
      "Space for extra bedding",
      "King size bed",
      "Luggage stand",
      "Mountain view",
    ],
    images: [
      "/images/rooms/mohru-1.jpg",
      "/images/rooms/mohru-2.jpg",
      "/images/rooms/mohru-3.jpg",
      "/images/rooms/mohru-4.jpg",
      "/images/rooms/mohru-5.jpg",
    ],
  },
  {
    id: 7,
    slug: "tosh",
    name: "Tosh",
    category: "Standard Room",
    size: "300 sq ft.",
    view: "Forest View",
    floor: "First Floor",
    description:
      "Having all the amenities of a deluxe room with the only difference of not having a valley view, Tosh is an easy choice if you want to grab the best deal for experiencing The Himalayan Shire. Its wooden interiors, handpicked carpet, a huge window with sheer as well as blackout curtains make it a really cozy place to stay in.",
    facilities: [
      "Space for extra bedding",
      "Huge window with sheer & blackout curtains",
      "Wooden interiors",
      "Handpicked carpet",
    ],
    images: [
      "/images/rooms/tosh-1.jpg",
      "/images/rooms/tosh-2.jpg",
      "/images/rooms/tosh-3.jpg",
      "/images/rooms/tosh-4.jpg",
      "/images/rooms/tosh-5.jpg",
    ],
  },
];